In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('GDP_capita.csv')

In [3]:
country_name_list = []
country_code_list = []
year_list = []
gdp_capita_list = []

# df.columns[4:len(df)-1]

for index, row in df.iterrows():
    country_name = row['Country Name']
    country_code = row['Country Code']
    for year in df.columns[4:len(df)-1]:
        if not np.isnan(row[year]):
            country_name_list.append(country_name)
            country_code_list.append(country_code)
            year_list.append(year)
            gdp_capita_list.append(row[year])

In [4]:
new_df = pd.DataFrame({'Country Name':country_name_list, 'Country Code': country_code_list, 'Year': year_list,
                       "GDP Capita": gdp_capita_list})

In [5]:
new_df.to_csv('GDP_capita_new.csv')

In [6]:
second_df = pd.read_csv('GDP.csv')

In [7]:
country_name_list = []
country_code_list = []
year_list = []
gdp_list = []

for index, row in second_df.iterrows():
    country_name = row['Country Name']
    country_code = row['Country Code']
    for year in second_df.columns[4:len(df)-1]:
        if not np.isnan(row[year]):
            country_name_list.append(country_name)
            country_code_list.append(country_code)
            year_list.append(year)
            gdp_list.append(row[year])

In [8]:
second_new_df = pd.DataFrame({'Country Name':country_name_list, 'Country Code': country_code_list, 'Year': year_list,
                       "GDP": gdp_list})

In [9]:
second_new_df = second_new_df.dropna()

In [10]:
second_new_df.to_csv('GDP_new.csv')

In [11]:
pop_df = pd.read_csv("population.csv", sep='\t')

In [12]:
country_name_list = []
country_code_list = []
year_list = []
pop_list = []

for index, row in pop_df.iterrows():
    country_name = row['Country Name']
    country_code = row['Country Code']
    for year in pop_df.columns[4:len(df)-1]:
        if not np.isnan(row[year]):
            country_name_list.append(country_name)
            country_code_list.append(country_code)
            year_list.append(year)
            pop_list.append(row[year])

In [13]:
pop_new_df = pd.DataFrame({'Country Name':country_name_list, 'Country Code': country_code_list, 'Year': year_list,
                       "Population": pop_list})

In [14]:
pop_new_df = pop_new_df.dropna()

In [15]:
pop_new_df.to_csv("population_new.csv")

In [16]:
new_full_df = pd.merge(second_new_df, pop_new_df,  how='left', left_on=['Country Name','Country Code', 'Year'], right_on = ['Country Name','Country Code', 'Year'])

In [17]:
new_full_df

      Country Name Country Code  Year           GDP  Population
0          Albania          ALB  1994  1.330168e+09   3207536.0
1          Albania          ALB  1995  1.320670e+09   3187784.0
2          Albania          ALB  1996  1.379888e+09   3168033.0
3          Albania          ALB  1997  1.531844e+09   3148281.0
4          Albania          ALB  1998  1.665363e+09   3128530.0
5          Albania          ALB  1999  1.722799e+09   3108778.0
6          Albania          ALB  2000  1.873453e+09   3089027.0
7          Albania          ALB  2001  1.920263e+09   3060173.0
8          Albania          ALB  2002  1.941095e+09   3051010.0
9          Albania          ALB  2003  2.021302e+09   3039616.0
10         Albania          ALB  2004  2.228279e+09   3026939.0
11         Albania          ALB  2005  2.331006e+09   3011487.0
12         Albania          ALB  2006  2.421475e+09   2992547.0
13         Albania          ALB  2007  2.623726e+09   2970017.0
14         Albania          ALB  2008  2.791961e+09   2947314.0
15         Albania          ALB  2009  2.498933e+09   2927519.0
16         Albania          ALB  2010  2.467704e+09   2913021.0
17         Albania          ALB  2011  2.584464e+09   2905195.0
18         Andorra          AND  1960  5.377778e+08     13411.0
19         Andorra          AND  1961  5.488889e+08     14375.0
20         Andorra          AND  1962  5.466667e+08     15370.0
21         Andorra          AND  1963  7.511112e+08     16412.0
22         Andorra          AND  1964  8.000000e+08     17469.0
23         Andorra          AND  1965  1.006667e+09     18549.0
24         Andorra          AND  1966  1.400000e+09     19647.0
25         Andorra          AND  1967  1.673333e+09     20758.0
26         Andorra          AND  1968  1.373333e+09     21890.0
27         Andorra          AND  1969  1.408889e+09     23058.0
28         Andorra          AND  1970  1.748887e+09     24276.0
29         Andorra          AND  1971  1.831109e+09     25559.0
...            ...          ...   ...           ...         ...
11573       Zambia          ZMB  2015  6.439947e+09  16100587.0
11574       Zambia          ZMB  2016  6.715487e+09  16591390.0
11575       Zambia          ZMB  2017  7.128691e+09  17094130.0
11576     Zimbabwe          ZWE  1990  5.647252e+09  10183113.0
11577     Zimbabwe          ZWE  1991  5.930370e+09  10443043.0
11578     Zimbabwe          ZWE  1992  6.463650e+09  10682868.0
11579     Zimbabwe          ZWE  1993  5.368271e+09  10905756.0
11580     Zimbabwe          ZWE  1994  4.167356e+09  11116948.0
11581     Zimbabwe          ZWE  1995  4.258789e+09  11320346.0
11582     Zimbabwe          ZWE  1996  5.785685e+09  11518262.0
11583     Zimbabwe          ZWE  1997  6.839039e+09  11709997.0
11584     Zimbabwe          ZWE  1998  6.325220e+09  11893272.0
11585     Zimbabwe          ZWE  1999  7.641101e+09  12064537.0
11586     Zimbabwe          ZWE  2000  9.636342e+09  12222251.0
11587     Zimbabwe          ZWE  2001  9.854042e+09  12366165.0
11588     Zimbabwe          ZWE  2002  1.069328e+10  12500525.0
11589     Zimbabwe          ZWE  2003  1.177777e+10  12633897.0
11590     Zimbabwe          ZWE  2004  1.387350e+10  12777511.0
11591     Zimbabwe          ZWE  2005  1.675377e+10  12940032.0
11592     Zimbabwe          ZWE  2006  1.908172e+10  13124267.0
11593     Zimbabwe          ZWE  2007  2.165652e+10  13329909.0
11594     Zimbabwe          ZWE  2008  2.691085e+10  13558469.0
11595     Zimbabwe          ZWE  2009  2.513027e+10  13810599.0
11596     Zimbabwe          ZWE  2010  3.090675e+10  14086317.0
11597     Zimbabwe          ZWE  2011  3.272642e+10  14386649.0
11598     Zimbabwe          ZWE  2012  3.540133e+10  14710826.0
11599     Zimbabwe          ZWE  2013  4.041524e+10  15054506.0
11600     Zimbabwe          ZWE  2014  4.322858e+10  15411675.0
11601     Zimbabwe          ZWE  2015  3.460248e+10  15777451.0
11602     Zimbabwe          ZWE  2016  1.821333e+10  16150362.0

[11603 rows x 5 columns]

In [18]:
new_full_df.to_csv('GDP_pop.csv')